### ISSUE TITLE
Smart Title Casing

### ISSUE THREAD

**Issue by mkormendy** [will-stone/in-any-case#1]
It'd be nice if there was a Smart Title Casing option that had the following capitalization rules:

1. By default, capitalize all words
2. Always capitalize the first and last word in titles and subtitles
3. Capitalize both parts of hyphenated words
4. Lowercase articles: a, an, the
5. Lowercase conjunctions: and, but, or, nor
6. Lowercase short prepositions: as, at, by, for, in, of, on, per, to, via
7. Lowercase versus: vs., vs, v., v
8. Lowercase NYT words*: en, if
9. Let intentional capitalization stand

This comes from the repository: https://github.com/gouch/to-title-case

**Comment by will-stone** [comment]
The trouble with white-listing word is for non-English languages; this could become quite hard to maintain.

**Comment by mkormendy** [comment]
Maybe some sort of flag to set the default language, and provide English to start.

**Comment by will-stone** [comment]
I'm thinking if I'm gonna do this, it'd be nice to create a Lodash addon for TitleText and then import that here. Here's my first go: https://codesandbox.io/s/damp-shadow-nb6gj

**Comment by will-stone** [comment]
I've been doing some perf testing. It seems like simply augmenting the lodash [startCase](https://github.com/lodash/lodash/blob/master/startCase.js) function is the best approach. Across browsers it seems like using an array or Map lookup is best, over using an object (which surprises me): https://codesandbox.io/s/happy-lumiere-nznqo
I think I'll go for array as it's the simplest. I'll release this as a separate package and then incorporate it into In any Case. Please note, it will conform to the same rules as lodash's startCase and simply lower any whitelisted words.

**Comment by mkormendy** [comment]
Depending on the array/object size performance can differ. Commonly, large data sets are better performed as objects, whereas small data sets are better as arrays. But this isn’t always the case depending on the data.

**Comment by will-stone** [comment]
Thanks! Good to know. Well, I think our array will mostly be quite small (unless it starts to support other languages).

**Comment by will-stone** [comment]
Released in v1.1.0

**Comment by mkormendy** [comment]
Works great! Thanks.
