### ISSUE TITLE
Carriage-Returns and Line-Feeds Unexpectedly Removed

### ISSUE THREAD

**Issue by mkormendy** [will-stone/in-any-case#2]
I have a bunch of lines of text, one after another, and when I attempt to Title Case the lines, it removes the carriage-return/line-feed. For example:

```
My dog is brown
My cat is white
```

Turns into:

```
My Dog Is Brown My Cat Is White
```

Can this be fixed?

**Comment by will-stone** [comment]
Thanks, I will look into it.

**Comment by will-stone** [comment]
I started to do this but realised that it's not a bug. A carriage return or tab or space _should_ be replaced, that is what a lodash function would do. If you want to keep the lines separate, you'll need to select them with multiple cursors.
